// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bwrfwhpktuvsjlrditbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cmZ3aHBrdHV2c2pscmRpdGJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4OTQ1OTksImV4cCI6MjA4OTQ3MDU5OX0.hWU4V_aTleNcqRNtuFE1Dzmh5C_sB1Mzyzszfe4vWOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);